"""Build the Kaggle evaluation notebook (08_test_ensemble.ipynb).

This notebook evaluates a trained checkpoint (single-worker OR 5-way
ensemble) on a fresh held-out synthetic test set and produces every
metric needed for the research paper:
  - Segmentation: per-class IoU, mIoU, fg_miou, binary_miou
  - OCR: CER, exact-match rate, character accuracy
  - Robustness slices: by font size bucket, by layout mode
  - Per-class IoU bar chart + simplified confusion matrix
  - Qualitative gallery (success + failure cases)
  - Inference speed (ms/image)
  - results.json + paper-ready markdown table

Re-run this script after editing the template:
    .venv/Scripts/python kaggle/_build_test_notebook.py
"""
from __future__ import annotations

import json
from pathlib import Path

KAGGLE_DIR = Path(__file__).parent
OUT_PATH = KAGGLE_DIR / "08_test_ensemble.ipynb"


def md(src: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": src}


def code(src: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": src,
    }


def build() -> dict:
    cells = [
        md(
            "# SegOCR — Test/Eval Notebook (paper metrics)\n\n"
            "Runs every metric reported in the research paper on a fresh "
            "held-out synthetic test set. Designed to be run **after** "
            "training is complete — attach either a single-worker checkpoint "
            "or the averaged ensemble `ensemble.pth`.\n\n"
            "**Setup:**\n"
            "1. Settings → Accelerator: **GPU T4** (T4 x2 also fine; only one used).\n"
            "2. Add Data: upload your trained `.pth` checkpoint as a Kaggle "
            "Dataset (e.g. `segocr-ensemble-checkpoint`) and attach it. Either "
            "`ensemble.pth` (preferred for headline numbers) or any single "
            "`averaged_best.pth` works — both load identically.\n"
            "3. Click **Save Version → Save & Run All**. Takes ~30-40 min "
            "(generation ~15 min + eval ~10 min + decode ~5 min).\n\n"
            "**Outputs:**\n"
            "- `/kaggle/working/results.json` — all metrics, machine-readable\n"
            "- `/kaggle/working/results_paper_table.md` — markdown table for the paper\n"
            "- `/kaggle/working/per_class_iou.png` — per-class IoU bar chart\n"
            "- `/kaggle/working/qualitative_gallery.png` — success + failure cases"
        ),
        md("## 1 / Setup — clone repo + install deps"),
        code(
            "import os\n"
            "if not os.path.isdir('/kaggle/working/segocr'):\n"
            "    !git clone https://github.com/mauryantitans/SegOCR.git /kaggle/working/segocr\n"
            "%cd /kaggle/working/segocr\n"
            "!git pull --quiet\n"
            "!pip install -q -e .\n"
            "!pip install -q -r requirements/base.txt\n"
            "!pip install -q segmentation-models-pytorch"
        ),
        md("## 2 / Verify GPU"),
        code(
            "import torch\n"
            "if not torch.cuda.is_available():\n"
            "    raise RuntimeError('No GPU. Settings → Accelerator → GPU T4.')\n"
            "DEVICE = torch.device('cuda:0')\n"
            "print(f'GPU: {torch.cuda.get_device_name(0)}')\n"
            "print(f'Mem: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')"
        ),
        md(
            "## 3 / Locate the trained checkpoint\n\n"
            "Searches `/kaggle/input/` for `.pth` files. If multiple are "
            "found (e.g. you attached all 5 worker checkpoints), they're "
            "averaged on the fly into an ensemble — equivalent to running "
            "`scripts/average_runs.py` locally."
        ),
        code(
            "import glob\n"
            "\n"
            "candidates = []\n"
            "for pat in (\n"
            "    '/kaggle/input/*/ensemble.pth',\n"
            "    '/kaggle/input/*/averaged_best.pth',\n"
            "    '/kaggle/input/*/*.pth',\n"
            "    '/kaggle/input/*/*/*.pth',\n"
            "):\n"
            "    candidates.extend(glob.glob(pat))\n"
            "candidates = sorted(set(candidates))\n"
            "if not candidates:\n"
            "    raise FileNotFoundError(\n"
            "        'No .pth checkpoints found under /kaggle/input/. Attach a Dataset '\n"
            "        'containing ensemble.pth (or averaged_best.pth files).'\n"
            "    )\n"
            "print(f'Found {len(candidates)} checkpoint(s):')\n"
            "for p in candidates:\n"
            "    sz = os.path.getsize(p) / 1e6\n"
            "    print(f'  {p}  ({sz:.1f} MB)')\n"
            "\n"
            "CHECKPOINT_PATHS = candidates"
        ),
        md(
            "## 4 / Generate a held-out test set\n\n"
            "1,000 fresh synthetic samples at indices `[80000, 81000)` — "
            "outside the range any training worker used (workers 0-4 "
            "consumed indices `[0, 80000)`). Generation takes ~10-15 min "
            "on Kaggle CPU. Skips automatically if a previous run's output "
            "is attached."
        ),
        code(
            "import os, glob, time\n"
            "\n"
            "TEST_SET_SIZE = 1_000\n"
            "TEST_INDEX_OFFSET = 80_000\n"
            "TEST_DIR = '/kaggle/working/test_set'\n"
            "\n"
            "# Reuse pre-generated test set if attached as a dataset\n"
            "prev_test_dirs = [\n"
            "    p for p in glob.glob('/kaggle/input/*/test_set')\n"
            "    if os.path.isdir(os.path.join(p, 'images'))\n"
            "]\n"
            "if prev_test_dirs:\n"
            "    src = prev_test_dirs[0]\n"
            "    print(f'Reusing pre-generated test set: {src}')\n"
            "    TEST_DIR = src\n"
            "elif (os.path.isdir(f'{TEST_DIR}/images')\n"
            "      and len(os.listdir(f'{TEST_DIR}/images')) >= TEST_SET_SIZE):\n"
            "    print(f'Test set already present at {TEST_DIR}; skipping generation.')\n"
            "else:\n"
            "    import yaml\n"
            "    from pathlib import Path\n"
            "    cfg = yaml.safe_load(Path('segocr/configs/default.yaml').read_text())\n"
            "    cfg['generator']['fonts']['root_dir'] = '/usr/share/fonts'\n"
            "    cfg['generator']['fonts']['cache_path'] = '/kaggle/working/font_cache.json'\n"
            "    cfg['generator']['fonts']['min_size'] = 40\n"
            "    cfg['generator']['fonts']['max_size'] = 128\n"
            "    cfg['generator']['image_size'] = [512, 512]\n"
            "    cfg['generator']['num_workers'] = 2\n"
            "    cfg['generator']['text']['min_length'] = 2\n"
            "    cfg['generator']['text']['max_length'] = 20\n"
            "    cfg['generator']['text']['min_words_per_line'] = 1\n"
            "    cfg['generator']['text']['max_words_per_line'] = 3\n"
            "    cfg['generator']['text']['max_lines'] = 1\n"
            "    cfg['generator']['text']['case_distribution'] = {\n"
            "        'lower': 0.50, 'upper': 0.20, 'mixed': 0.20, 'title': 0.10,\n"
            "    }\n"
            "    cfg['generator']['text']['rare_char_boost'] = 4.0\n"
            "    cfg['generator']['text']['corpus_paths'] = [\n"
            "        {'path': 'BUNDLED:signs', 'tag': 'signs', 'weight': 0.30},\n"
            "        {'path': 'BUNDLED:receipts', 'tag': 'receipts', 'weight': 0.20},\n"
            "        {'path': 'BUNDLED:names', 'tag': 'names', 'weight': 0.20},\n"
            "        {'path': 'BUNDLED:numbers', 'tag': 'numbers', 'weight': 0.30},\n"
            "    ]\n"
            "    cfg['generator']['layout']['modes'] = {\n"
            "        'horizontal': 0.50, 'rotated': 0.20, 'curved': 0.10,\n"
            "        'perspective': 0.10, 'deformed': 0.10, 'paragraph': 0.0,\n"
            "    }\n"
            "    cfg['generator']['background']['natural_image_dirs'] = []\n"
            "    test_cfg_path = '/kaggle/working/test_gen_config.yaml'\n"
            "    Path(test_cfg_path).write_text(yaml.safe_dump(cfg))\n"
            "    print(f'Generating {TEST_SET_SIZE} held-out samples at indices [{TEST_INDEX_OFFSET}, {TEST_INDEX_OFFSET + TEST_SET_SIZE})...')\n"
            "    t0 = time.time()\n"
            "    !python -m scripts.generate_dataset --config {test_cfg_path} --num-images {TEST_SET_SIZE} --output {TEST_DIR} --index-offset {TEST_INDEX_OFFSET}\n"
            "    print(f'Generation done in {(time.time() - t0)/60:.1f} min')\n"
            "\n"
            "n_imgs = len(os.listdir(f'{TEST_DIR}/images'))\n"
            "print(f'Test set ready: {TEST_DIR} ({n_imgs} samples)')"
        ),
        md(
            "## 5 / Build model + load weights\n\n"
            "If multiple checkpoints were found, average them (equivalent "
            "to the offline `scripts.average_runs` flow). Otherwise load "
            "the single checkpoint."
        ),
        code(
            "import yaml\n"
            "from pathlib import Path\n"
            "from segocr.models.unet import build_model\n"
            "\n"
            "cfg = yaml.safe_load(Path('segocr/configs/default.yaml').read_text())\n"
            "cfg['model']['architecture'] = 'unet'\n"
            "cfg['model']['encoder'] = 'resnet18'\n"
            "cfg['model']['encoder_weights'] = None   # weights come from checkpoint\n"
            "cfg['model']['head_features'] = 64\n"
            "cfg['model']['decoder_channels'] = [256, 128, 64, 32, 32]\n"
            "cfg['model']['heads'] = {'semantic': True, 'affinity': True, 'direction': True}\n"
            "cfg['model']['num_classes'] = 63\n"
            "cfg['model']['input_size'] = [512, 512]\n"
            "\n"
            "model = build_model(cfg['model']).to(DEVICE)\n"
            "\n"
            "def _extract_state_dict(ckpt):\n"
            "    if 'model' in ckpt:\n"
            "        return ckpt['model']\n"
            "    if 'ema' in ckpt:\n"
            "        return ckpt['ema']\n"
            "    return ckpt\n"
            "\n"
            "if len(CHECKPOINT_PATHS) == 1:\n"
            "    ckpt = torch.load(CHECKPOINT_PATHS[0], map_location=DEVICE)\n"
            "    state = _extract_state_dict(ckpt)\n"
            "    print(f'Loaded single checkpoint: {CHECKPOINT_PATHS[0]}')\n"
            "else:\n"
            "    states = [_extract_state_dict(torch.load(p, map_location='cpu')) for p in CHECKPOINT_PATHS]\n"
            "    state = {}\n"
            "    for key in states[0]:\n"
            "        if not torch.is_tensor(states[0][key]) or not states[0][key].is_floating_point():\n"
            "            state[key] = states[0][key]\n"
            "            continue\n"
            "        stacked = torch.stack([s[key].float() for s in states])\n"
            "        state[key] = stacked.mean(dim=0).to(states[0][key].dtype)\n"
            "    print(f'Averaged {len(states)} checkpoints into an ensemble.')\n"
            "\n"
            "model.load_state_dict(state)\n"
            "model.eval()\n"
            "n_params = sum(p.numel() for p in model.parameters())\n"
            "print(f'Model: {n_params/1e6:.2f}M params')"
        ),
        md(
            "## 6 / Section A — Segmentation metrics\n\n"
            "Streaming confusion matrix over the full test set → mIoU, "
            "fg_miou, binary_miou, per-class IoU. These are the headline "
            "segmentation numbers."
        ),
        code(
            "import numpy as np\n"
            "from torch.utils.data import DataLoader\n"
            "from segocr.training.dataset import SegOCRDataset, collate_fn\n"
            "from segocr.training.evaluator import Evaluator\n"
            "from segocr.evaluation.metrics import miou, fg_miou, binary_miou\n"
            "\n"
            "NUM_CLASSES = 63\n"
            "BATCH_SIZE = 8   # small for safety; eval is single-pass\n"
            "\n"
            "test_ds = SegOCRDataset(TEST_DIR, split='train', train_aug=False)\n"
            "# split='train' covers ALL files since the hash-split uses 5%% for val;\n"
            "# we want the full 1K samples, not 950.\n"
            "test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False,\n"
            "                          num_workers=2, collate_fn=collate_fn)\n"
            "\n"
            "evaluator = Evaluator(num_classes=NUM_CLASSES, device=DEVICE)\n"
            "evaluator.reset()\n"
            "with torch.no_grad():\n"
            "    for batch in test_loader:\n"
            "        images = batch['image'].to(DEVICE, non_blocking=True)\n"
            "        targets = batch['targets']['semantic'].to(DEVICE, non_blocking=True)\n"
            "        outputs = model(images)\n"
            "        preds = outputs['semantic'].argmax(dim=1)\n"
            "        evaluator.update(preds, targets)\n"
            "\n"
            "cm = evaluator.confusion_matrix.cpu().numpy()\n"
            "seg_metrics = {\n"
            "    'miou': miou(cm),\n"
            "    'fg_miou': fg_miou(cm),\n"
            "    'binary_miou': binary_miou(cm),\n"
            "}\n"
            "print('Segmentation metrics:')\n"
            "for k, v in seg_metrics.items():\n"
            "    print(f'  {k:15s} {v:.4f}')\n"
            "\n"
            "# Per-class IoU\n"
            "diag = np.diag(cm).astype(np.float64)\n"
            "row = cm.sum(axis=1)\n"
            "col = cm.sum(axis=0)\n"
            "per_class_iou = (diag + 1e-9) / (row + col - diag + 1e-9)\n"
            "print(f'\\nPer-class IoU range: [{per_class_iou[1:].min():.3f}, {per_class_iou[1:].max():.3f}]')\n"
            "print(f'Mean foreground IoU: {per_class_iou[1:].mean():.3f}')"
        ),
        md(
            "## 7 / Section B — OCR-level metrics (decode → CER, exact-match)\n\n"
            "For each test image: argmax + max-softmax → "
            "`cleanup_prediction` → `extract_instances` → `recover_text` → "
            "compare to ground-truth string. Reports CER, normalized edit "
            "distance, exact-match rate. The decoder uses our trained "
            "char-level segmentation, no language model."
        ),
        code(
            "import json\n"
            "import torch.nn.functional as F\n"
            "from segocr.postprocessing.cleanup import cleanup_prediction\n"
            "from segocr.postprocessing.instance_extraction import extract_instances\n"
            "from segocr.postprocessing.reading_order import recover_text\n"
            "from segocr.evaluation.metrics import cer, ned, exact_match\n"
            "\n"
            "def _gt_string_from_metadata(meta_path):\n"
            "    '''Reconstruct the ground-truth string from the per-char metadata\n"
            "    using reading-order recovery (same pipeline as the prediction).'''\n"
            "    with open(meta_path, encoding='utf-8') as f:\n"
            "        m = json.load(f)\n"
            "    # The on-disk metadata has each character's bbox + class_id.\n"
            "    # Bbox is stored at supersampled scale — but the renderer scales\n"
            "    # it back via the `scale` factor; here we just use the centroids\n"
            "    # for ordering. As a robust fallback we just take char order as\n"
            "    # rendered (Latin reading order is x-then-y).\n"
            "    chars = m.get('characters', [])\n"
            "    if not chars:\n"
            "        return ''\n"
            "    return ''.join(c['char'] for c in chars)\n"
            "\n"
            "per_sample_results = []\n"
            "with torch.no_grad():\n"
            "    for batch in test_loader:\n"
            "        images = batch['image'].to(DEVICE, non_blocking=True)\n"
            "        outputs = model(images)\n"
            "        logits = outputs['semantic']                          # (B, C, H, W)\n"
            "        probs = F.softmax(logits, dim=1)\n"
            "        preds = probs.argmax(dim=1).cpu().numpy()             # (B, H, W)\n"
            "        confs = probs.max(dim=1).values.cpu().numpy()         # (B, H, W)\n"
            "        for i, info in enumerate(batch['metadata']):\n"
            "            name = info['name']\n"
            "            meta_path = f'{TEST_DIR}/metadata/{name}.json'\n"
            "            gt = _gt_string_from_metadata(meta_path)\n"
            "            clean = cleanup_prediction(preds[i], confs[i],\n"
            "                                       threshold=0.5, min_component_area=20)\n"
            "            instances = extract_instances(clean, min_size=8, max_size=256)\n"
            "            pred_text = recover_text(instances)\n"
            "            per_sample_results.append({\n"
            "                'name': name,\n"
            "                'gt': gt,\n"
            "                'pred': pred_text,\n"
            "                'cer': cer(pred_text, gt),\n"
            "                'ned': ned(pred_text, gt),\n"
            "                'exact_match': exact_match(pred_text, gt),\n"
            "            })\n"
            "\n"
            "import statistics\n"
            "ocr_metrics = {\n"
            "    'cer_mean':         statistics.mean(r['cer'] for r in per_sample_results),\n"
            "    'ned_mean':         statistics.mean(r['ned'] for r in per_sample_results),\n"
            "    'exact_match_rate': statistics.mean(r['exact_match'] for r in per_sample_results),\n"
            "    'samples':          len(per_sample_results),\n"
            "}\n"
            "print('OCR metrics:')\n"
            "for k, v in ocr_metrics.items():\n"
            "    print(f'  {k:18s} {v:.4f}' if isinstance(v, float) else f'  {k:18s} {v}')"
        ),
        md(
            "## 8 / Section C — Robustness slices\n\n"
            "Stratifies the per-sample CER and exact-match rate by:\n"
            "- **Font size bucket** (small / medium / large — derived from "
            "median character bbox height)\n"
            "- **Layout mode** (horizontal / rotated / curved / perspective / "
            "deformed)\n\n"
            "Reviewers love these — they show *where* the model fails, "
            "not just an aggregate number."
        ),
        code(
            "from collections import defaultdict\n"
            "\n"
            "def _load_meta(name):\n"
            "    with open(f'{TEST_DIR}/metadata/{name}.json', encoding='utf-8') as f:\n"
            "        return json.load(f)\n"
            "\n"
            "def _font_size_bucket(meta):\n"
            "    chars = meta.get('characters', [])\n"
            "    if not chars:\n"
            "        return 'unknown'\n"
            "    heights = [c['bbox'][3] - c['bbox'][1] for c in chars]\n"
            "    h = statistics.median(heights) if heights else 0\n"
            "    if h < 40:    return 'small'\n"
            "    if h < 80:    return 'medium'\n"
            "    return 'large'\n"
            "\n"
            "by_size = defaultdict(list)\n"
            "by_layout = defaultdict(list)\n"
            "for r in per_sample_results:\n"
            "    meta = _load_meta(r['name'])\n"
            "    by_size[_font_size_bucket(meta)].append(r)\n"
            "    by_layout[meta.get('layout_mode', 'unknown')].append(r)\n"
            "\n"
            "def _agg(group):\n"
            "    return {\n"
            "        'n':                len(group),\n"
            "        'cer_mean':         statistics.mean(r['cer'] for r in group),\n"
            "        'exact_match_rate': statistics.mean(r['exact_match'] for r in group),\n"
            "    }\n"
            "\n"
            "robustness = {\n"
            "    'by_font_size': {k: _agg(v) for k, v in by_size.items()},\n"
            "    'by_layout':    {k: _agg(v) for k, v in by_layout.items()},\n"
            "}\n"
            "\n"
            "print('--- By font size ---')\n"
            "for k, m in sorted(robustness['by_font_size'].items()):\n"
            "    print(f'  {k:8s}  n={m[\"n\"]:4d}  CER={m[\"cer_mean\"]:.3f}  EM={m[\"exact_match_rate\"]:.3f}')\n"
            "print('--- By layout mode ---')\n"
            "for k, m in sorted(robustness['by_layout'].items()):\n"
            "    print(f'  {k:12s}  n={m[\"n\"]:4d}  CER={m[\"cer_mean\"]:.3f}  EM={m[\"exact_match_rate\"]:.3f}')"
        ),
        md(
            "## 9 / Section D — Per-class IoU bar chart\n\n"
            "One bar per character class (0=background, 1-26=A-Z, 27-52=a-z, "
            "53-62=0-9). Drops the headline 'j' visualization that motivates "
            "the rare-character story in the paper."
        ),
        code(
            "import matplotlib.pyplot as plt\n"
            "import string\n"
            "\n"
            "labels = ['bg'] + list(string.ascii_uppercase + string.ascii_lowercase + string.digits)\n"
            "ious = per_class_iou\n"
            "fig, ax = plt.subplots(figsize=(16, 4))\n"
            "colors = ['gray'] + ['steelblue'] * 26 + ['darkorange'] * 26 + ['seagreen'] * 10\n"
            "ax.bar(range(len(labels)), ious, color=colors)\n"
            "ax.set_xticks(range(len(labels)))\n"
            "ax.set_xticklabels(labels, fontsize=8)\n"
            "ax.set_ylabel('IoU')\n"
            "ax.set_title('Per-class IoU')\n"
            "ax.axhline(per_class_iou[1:].mean(), color='red', linestyle='--', linewidth=1, label='fg mean')\n"
            "ax.legend()\n"
            "ax.set_ylim(0, 1)\n"
            "plt.tight_layout()\n"
            "plt.savefig('/kaggle/working/per_class_iou.png', dpi=150, bbox_inches='tight')\n"
            "plt.show()\n"
            "\n"
            "# Print bottom-10 classes — these are the rare ones the paper should call out\n"
            "fg_iou_pairs = sorted(\n"
            "    [(labels[i], float(per_class_iou[i])) for i in range(1, len(labels))],\n"
            "    key=lambda kv: kv[1],\n"
            ")\n"
            "print('\\nWorst-performing 10 classes:')\n"
            "for ch, v in fg_iou_pairs[:10]:\n"
            "    print(f'  {ch!r:6s}  IoU={v:.3f}')"
        ),
        md(
            "## 10 / Section E — Qualitative gallery\n\n"
            "8 success cases (exact_match=1) + 8 failure cases (highest CER). "
            "Use these in the paper's qualitative figure. Layout: 4×4 grid, "
            "each tile shows image + GT + predicted text."
        ),
        code(
            "from PIL import Image\n"
            "import matplotlib.pyplot as plt\n"
            "\n"
            "successes = [r for r in per_sample_results if r['exact_match'] == 1.0][:8]\n"
            "failures = sorted(per_sample_results, key=lambda r: -r['cer'])[:8]\n"
            "samples = successes + failures\n"
            "\n"
            "fig, axes = plt.subplots(4, 4, figsize=(16, 16))\n"
            "for ax, r in zip(axes.flat, samples, strict=False):\n"
            "    img = Image.open(f'{TEST_DIR}/images/{r[\"name\"]}.png')\n"
            "    ax.imshow(img)\n"
            "    status = 'OK' if r['exact_match'] == 1.0 else f'CER={r[\"cer\"]:.2f}'\n"
            "    ax.set_title(f'{status}\\nGT:   {r[\"gt\"][:30]}\\nPred: {r[\"pred\"][:30]}',\n"
            "                 fontsize=8, loc='left')\n"
            "    ax.axis('off')\n"
            "plt.tight_layout()\n"
            "plt.savefig('/kaggle/working/qualitative_gallery.png', dpi=120, bbox_inches='tight')\n"
            "plt.show()"
        ),
        md(
            "## 11 / Section F — Inference speed\n\n"
            "Warms the GPU then times forward passes for a batch of 8. "
            "Reports ms/image and FPS — basic efficiency numbers reviewers ask for."
        ),
        code(
            "import time\n"
            "\n"
            "# Warmup\n"
            "warmup_batch = next(iter(test_loader))\n"
            "warmup_images = warmup_batch['image'].to(DEVICE)\n"
            "with torch.no_grad():\n"
            "    for _ in range(3):\n"
            "        _ = model(warmup_images)\n"
            "torch.cuda.synchronize()\n"
            "\n"
            "n_batches = 0\n"
            "n_images = 0\n"
            "t0 = time.perf_counter()\n"
            "with torch.no_grad():\n"
            "    for batch in test_loader:\n"
            "        images = batch['image'].to(DEVICE, non_blocking=True)\n"
            "        _ = model(images)\n"
            "        n_batches += 1\n"
            "        n_images += images.shape[0]\n"
            "        if n_batches >= 25:    # ~200 images is enough for a stable mean\n"
            "            break\n"
            "torch.cuda.synchronize()\n"
            "elapsed = time.perf_counter() - t0\n"
            "ms_per_image = (elapsed / n_images) * 1000\n"
            "fps = n_images / elapsed\n"
            "speed = {'ms_per_image': ms_per_image, 'fps': fps, 'n_images': n_images}\n"
            "print(f'Speed: {ms_per_image:.1f} ms/image  ({fps:.1f} FPS, batch={BATCH_SIZE})')"
        ),
        md(
            "## 12 / Section G — Export results\n\n"
            "Dumps everything to `/kaggle/working/results.json` (machine-"
            "readable for the paper-build pipeline) and writes a markdown "
            "table you can paste directly into the LaTeX/Markdown manuscript."
        ),
        code(
            "import json\n"
            "\n"
            "results = {\n"
            "    'checkpoints_used': CHECKPOINT_PATHS,\n"
            "    'n_test_samples': ocr_metrics['samples'],\n"
            "    'segmentation': seg_metrics,\n"
            "    'ocr': ocr_metrics,\n"
            "    'robustness': robustness,\n"
            "    'speed': speed,\n"
            "    'per_class_iou': {labels[i]: float(per_class_iou[i]) for i in range(len(labels))},\n"
            "    'model_params_M': float(n_params / 1e6),\n"
            "}\n"
            "\n"
            "with open('/kaggle/working/results.json', 'w', encoding='utf-8') as f:\n"
            "    json.dump(results, f, indent=2)\n"
            "print('Wrote /kaggle/working/results.json')\n"
            "\n"
            "# Build a paper-ready markdown table\n"
            "md_lines = [\n"
            "    '## SegOCR results',\n"
            "    '',\n"
            "    '### Segmentation',\n"
            "    '',\n"
            "    '| Metric | Value |',\n"
            "    '|---|---|',\n"
            "    f'| mIoU | {seg_metrics[\"miou\"]:.3f} |',\n"
            "    f'| fg mIoU | {seg_metrics[\"fg_miou\"]:.3f} |',\n"
            "    f'| Binary mIoU | {seg_metrics[\"binary_miou\"]:.3f} |',\n"
            "    '',\n"
            "    '### OCR',\n"
            "    '',\n"
            "    '| Metric | Value |',\n"
            "    '|---|---|',\n"
            "    f'| CER (mean) | {ocr_metrics[\"cer_mean\"]:.3f} |',\n"
            "    f'| NED (mean) | {ocr_metrics[\"ned_mean\"]:.3f} |',\n"
            "    f'| Exact match | {ocr_metrics[\"exact_match_rate\"]:.3f} |',\n"
            "    '',\n"
            "    '### Robustness — by font size',\n"
            "    '',\n"
            "    '| Bucket | N | CER | Exact match |',\n"
            "    '|---|---|---|---|',\n"
            "]\n"
            "for k in ('small', 'medium', 'large'):\n"
            "    m = robustness['by_font_size'].get(k)\n"
            "    if m:\n"
            "        md_lines.append(f'| {k} | {m[\"n\"]} | {m[\"cer_mean\"]:.3f} | {m[\"exact_match_rate\"]:.3f} |')\n"
            "md_lines += ['', '### Robustness — by layout mode', '', '| Mode | N | CER | Exact match |', '|---|---|---|---|']\n"
            "for k, m in sorted(robustness['by_layout'].items()):\n"
            "    md_lines.append(f'| {k} | {m[\"n\"]} | {m[\"cer_mean\"]:.3f} | {m[\"exact_match_rate\"]:.3f} |')\n"
            "md_lines += ['', '### Efficiency', '', '| Metric | Value |', '|---|---|',\n"
            "             f'| Params (M) | {results[\"model_params_M\"]:.2f} |',\n"
            "             f'| Inference ms/image | {speed[\"ms_per_image\"]:.1f} |',\n"
            "             f'| FPS @ batch={BATCH_SIZE} | {speed[\"fps\"]:.1f} |']\n"
            "\n"
            "with open('/kaggle/working/results_paper_table.md', 'w', encoding='utf-8') as f:\n"
            "    f.write('\\n'.join(md_lines))\n"
            "print('Wrote /kaggle/working/results_paper_table.md')\n"
            "print()\n"
            "print('\\n'.join(md_lines))"
        ),
    ]

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.10"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    nb = build()
    OUT_PATH.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {OUT_PATH}  ({len(nb['cells'])} cells)")


if __name__ == "__main__":
    main()
